apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qubership-apihub-test-service
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  labels:
    app.kubernetes.io/part-of: qubership-apihub-test-service
    app.kubernetes.io/managed-by: helm
spec:
  rules:
  - host: qubership-apihub-test-service.localtest.me
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: qubership-apihub-test-service
            port:
              name: web
